apiVersion: v1
kind: Service
metadata:
  name: account-aggregator
  labels:
    app: account-aggregator
    service: account-aggregator
spec:
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 8000
    targetPort: 8000
  selector:
    app: account-aggregator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: account-aggregator
