FROM soarinferret/iptablesproxy

WORKDIR /root

# Install prerequisities.
RUN apk update && apk upgrade && apk add bash

# Copy scripts for setting up the CCR for sandboxing.
COPY config/setup-iptables.sh setup-iptables.sh

# Make sure the line endings are LF for Linux.
RUN dos2unix setup-iptables.sh

# Run a script for setting up the iptables for sandboxing.
ENTRYPOINT sh setup-iptables.sh
