apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/financial-information-user

patches:
- target:
    kind: Deployment
    name: financial-information-user
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: financial-information-user
    spec:
      template:
        spec:
          containers:
          - name: financial-information-user-service
            imagePullPolicy: Never
- target:
    kind: Service
    name: financial-information-user
  patch: |-
    apiVersion: v1
    kind: Service
    metadata:
      name: financial-information-user
    spec:
      type: ClusterIP