apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/oci-registry

patches:
- target:
    kind: Service
    name: oci-registry
  patch: |-
    apiVersion: v1
    kind: Service
    metadata:
      name: oci-registry
    spec:
      type: ClusterIP
