# The sidecar configuration.
sidecar:
  # The host of the CCR sidecar.
  host: 127.0.0.1
  # The port of the CCR sidecar.
  port: 8281
  # Configuration related to trusted local CCR containers.
  local:
    # The port of the local OPA policy engine.
    policy_engine:
      port: 8282
    # The port of the local crypto sidecar.
    crypto_sidecar:
      port: 8283
  # Configuration related to trusted external services.
  services:
    # The AA certificate registry.
    aa_cert_registry:
      uri: "http://certificate-registry:80/"
    # The type and URI of the key management service.
    key_management:
      # Only Azure is currently implemented.
      provider: azure-key-vault
      uri: "https://foo.vault.azure.net/"
