# Configuration for the business rule engine service.
apiVersion: v1
kind: Service
metadata:
  name: business-rule-engine
  labels:
    app: business-rule-engine
    service: business-rule-engine
spec:
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: business-rule-engine
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: business-rule-engine
