# Configuration for the statement analysis service.
apiVersion: v1
kind: Service
metadata:
  name: statement-analysis
  labels:
    app: statement-analysis
    service: statement-analysis
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 8080
  selector:
    app: statement-analysis
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: statement-analysis
